/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WhyTrustUsRouteImport } from './routes/why-trust-us'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceRequestRouteImport } from './routes/service-request'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LandlordRouteImport } from './routes/landlord'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'
import { Route as ReviewsServiceSlugRouteImport } from './routes/reviews.$serviceSlug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as HeatingInAreaSlugRouteImport } from './routes/heating-in.$areaSlug'
import { Route as GasBoilerInAreaSlugRouteImport } from './routes/gas-boiler-in.$areaSlug'
import { Route as ConfirmationRefIdRouteImport } from './routes/confirmation.$refId'
import { Route as AreasAreaSlugRouteImport } from './routes/areas.$areaSlug'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as CategoryAreaServiceRouteImport } from './routes/$categoryArea.$service'
import { Route as ServicesServiceSlugHowToRouteImport } from './routes/services.$serviceSlug.how-to'
import { Route as ServicesServiceSlugFaqsRouteImport } from './routes/services.$serviceSlug.faqs'
import { Route as ServicesServiceSlugAreaSlugRouteImport } from './routes/services.$serviceSlug.$areaSlug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyTrustUsRoute = WhyTrustUsRouteImport.update({
  id: '/why-trust-us',
  path: '/why-trust-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestRoute = ServiceRequestRouteImport.update({
  id: '/service-request',
  path: '/service-request',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => ServicesRoute,
} as any)
const ReviewsServiceSlugRoute = ReviewsServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => ReviewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const HeatingInAreaSlugRoute = HeatingInAreaSlugRouteImport.update({
  id: '/heating-in/$areaSlug',
  path: '/heating-in/$areaSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GasBoilerInAreaSlugRoute = GasBoilerInAreaSlugRouteImport.update({
  id: '/gas-boiler-in/$areaSlug',
  path: '/gas-boiler-in/$areaSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRefIdRoute = ConfirmationRefIdRouteImport.update({
  id: '/confirmation/$refId',
  path: '/confirmation/$refId',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaSlugRoute = AreasAreaSlugRouteImport.update({
  id: '/areas/$areaSlug',
  path: '/areas/$areaSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/admin/portfolio',
  path: '/admin/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryAreaServiceRoute = CategoryAreaServiceRouteImport.update({
  id: '/$categoryArea/$service',
  path: '/$categoryArea/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceSlugHowToRoute =
  ServicesServiceSlugHowToRouteImport.update({
    id: '/how-to',
    path: '/how-to',
    getParentRoute: () => ServicesServiceSlugRoute,
  } as any)
const ServicesServiceSlugFaqsRoute = ServicesServiceSlugFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => ServicesServiceSlugRoute,
} as any)
const ServicesServiceSlugAreaSlugRoute =
  ServicesServiceSlugAreaSlugRouteImport.update({
    id: '/$areaSlug',
    path: '/$areaSlug',
    getParentRoute: () => ServicesServiceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/commercial': typeof CommercialRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/finance': typeof FinanceRoute
  '/landlord': typeof LandlordRoute
  '/news': typeof NewsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/safety': typeof SafetyRoute
  '/service-request': typeof ServiceRequestRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/why-trust-us': typeof WhyTrustUsRoute
  '/work': typeof WorkRouteWithChildren
  '/$categoryArea/$service': typeof CategoryAreaServiceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/areas/$areaSlug': typeof AreasAreaSlugRoute
  '/confirmation/$refId': typeof ConfirmationRefIdRoute
  '/gas-boiler-in/$areaSlug': typeof GasBoilerInAreaSlugRoute
  '/heating-in/$areaSlug': typeof HeatingInAreaSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/reviews/$serviceSlug': typeof ReviewsServiceSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRouteWithChildren
  '/work/$slug': typeof WorkSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/services/$serviceSlug/$areaSlug': typeof ServicesServiceSlugAreaSlugRoute
  '/services/$serviceSlug/faqs': typeof ServicesServiceSlugFaqsRoute
  '/services/$serviceSlug/how-to': typeof ServicesServiceSlugHowToRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/commercial': typeof CommercialRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/finance': typeof FinanceRoute
  '/landlord': typeof LandlordRoute
  '/news': typeof NewsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/safety': typeof SafetyRoute
  '/service-request': typeof ServiceRequestRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/why-trust-us': typeof WhyTrustUsRoute
  '/work': typeof WorkRouteWithChildren
  '/$categoryArea/$service': typeof CategoryAreaServiceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/areas/$areaSlug': typeof AreasAreaSlugRoute
  '/confirmation/$refId': typeof ConfirmationRefIdRoute
  '/gas-boiler-in/$areaSlug': typeof GasBoilerInAreaSlugRoute
  '/heating-in/$areaSlug': typeof HeatingInAreaSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/reviews/$serviceSlug': typeof ReviewsServiceSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRouteWithChildren
  '/work/$slug': typeof WorkSlugRoute
  '/areas': typeof AreasIndexRoute
  '/services/$serviceSlug/$areaSlug': typeof ServicesServiceSlugAreaSlugRoute
  '/services/$serviceSlug/faqs': typeof ServicesServiceSlugFaqsRoute
  '/services/$serviceSlug/how-to': typeof ServicesServiceSlugHowToRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/commercial': typeof CommercialRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/finance': typeof FinanceRoute
  '/landlord': typeof LandlordRoute
  '/news': typeof NewsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/safety': typeof SafetyRoute
  '/service-request': typeof ServiceRequestRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/why-trust-us': typeof WhyTrustUsRoute
  '/work': typeof WorkRouteWithChildren
  '/$categoryArea/$service': typeof CategoryAreaServiceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/areas/$areaSlug': typeof AreasAreaSlugRoute
  '/confirmation/$refId': typeof ConfirmationRefIdRoute
  '/gas-boiler-in/$areaSlug': typeof GasBoilerInAreaSlugRoute
  '/heating-in/$areaSlug': typeof HeatingInAreaSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/reviews/$serviceSlug': typeof ReviewsServiceSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRouteWithChildren
  '/work/$slug': typeof WorkSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/services/$serviceSlug/$areaSlug': typeof ServicesServiceSlugAreaSlugRoute
  '/services/$serviceSlug/faqs': typeof ServicesServiceSlugFaqsRoute
  '/services/$serviceSlug/how-to': typeof ServicesServiceSlugHowToRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout-success'
    | '/commercial'
    | '/complaints'
    | '/contact'
    | '/cookies'
    | '/emergency'
    | '/faq'
    | '/finance'
    | '/landlord'
    | '/news'
    | '/our-story'
    | '/pricing'
    | '/privacy'
    | '/reviews'
    | '/safety'
    | '/service-request'
    | '/services'
    | '/terms'
    | '/why-trust-us'
    | '/work'
    | '/$categoryArea/$service'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/portfolio'
    | '/areas/$areaSlug'
    | '/confirmation/$refId'
    | '/gas-boiler-in/$areaSlug'
    | '/heating-in/$areaSlug'
    | '/news/$slug'
    | '/reviews/$serviceSlug'
    | '/services/$serviceSlug'
    | '/work/$slug'
    | '/areas/'
    | '/services/$serviceSlug/$areaSlug'
    | '/services/$serviceSlug/faqs'
    | '/services/$serviceSlug/how-to'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout-success'
    | '/commercial'
    | '/complaints'
    | '/contact'
    | '/cookies'
    | '/emergency'
    | '/faq'
    | '/finance'
    | '/landlord'
    | '/news'
    | '/our-story'
    | '/pricing'
    | '/privacy'
    | '/reviews'
    | '/safety'
    | '/service-request'
    | '/services'
    | '/terms'
    | '/why-trust-us'
    | '/work'
    | '/$categoryArea/$service'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/portfolio'
    | '/areas/$areaSlug'
    | '/confirmation/$refId'
    | '/gas-boiler-in/$areaSlug'
    | '/heating-in/$areaSlug'
    | '/news/$slug'
    | '/reviews/$serviceSlug'
    | '/services/$serviceSlug'
    | '/work/$slug'
    | '/areas'
    | '/services/$serviceSlug/$areaSlug'
    | '/services/$serviceSlug/faqs'
    | '/services/$serviceSlug/how-to'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkout-success'
    | '/commercial'
    | '/complaints'
    | '/contact'
    | '/cookies'
    | '/emergency'
    | '/faq'
    | '/finance'
    | '/landlord'
    | '/news'
    | '/our-story'
    | '/pricing'
    | '/privacy'
    | '/reviews'
    | '/safety'
    | '/service-request'
    | '/services'
    | '/terms'
    | '/why-trust-us'
    | '/work'
    | '/$categoryArea/$service'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/portfolio'
    | '/areas/$areaSlug'
    | '/confirmation/$refId'
    | '/gas-boiler-in/$areaSlug'
    | '/heating-in/$areaSlug'
    | '/news/$slug'
    | '/reviews/$serviceSlug'
    | '/services/$serviceSlug'
    | '/work/$slug'
    | '/areas/'
    | '/services/$serviceSlug/$areaSlug'
    | '/services/$serviceSlug/faqs'
    | '/services/$serviceSlug/how-to'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CommercialRoute: typeof CommercialRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  EmergencyRoute: typeof EmergencyRoute
  FaqRoute: typeof FaqRoute
  FinanceRoute: typeof FinanceRoute
  LandlordRoute: typeof LandlordRoute
  NewsRoute: typeof NewsRouteWithChildren
  OurStoryRoute: typeof OurStoryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRouteWithChildren
  SafetyRoute: typeof SafetyRoute
  ServiceRequestRoute: typeof ServiceRequestRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  WhyTrustUsRoute: typeof WhyTrustUsRoute
  WorkRoute: typeof WorkRouteWithChildren
  CategoryAreaServiceRoute: typeof CategoryAreaServiceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AreasAreaSlugRoute: typeof AreasAreaSlugRoute
  ConfirmationRefIdRoute: typeof ConfirmationRefIdRoute
  GasBoilerInAreaSlugRoute: typeof GasBoilerInAreaSlugRoute
  HeatingInAreaSlugRoute: typeof HeatingInAreaSlugRoute
  AreasIndexRoute: typeof AreasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-trust-us': {
      id: '/why-trust-us'
      path: '/why-trust-us'
      fullPath: '/why-trust-us'
      preLoaderRoute: typeof WhyTrustUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-request': {
      id: '/service-request'
      path: '/service-request'
      fullPath: '/service-request'
      preLoaderRoute: typeof ServiceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord': {
      id: '/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/reviews/$serviceSlug': {
      id: '/reviews/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/reviews/$serviceSlug'
      preLoaderRoute: typeof ReviewsServiceSlugRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/heating-in/$areaSlug': {
      id: '/heating-in/$areaSlug'
      path: '/heating-in/$areaSlug'
      fullPath: '/heating-in/$areaSlug'
      preLoaderRoute: typeof HeatingInAreaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas-boiler-in/$areaSlug': {
      id: '/gas-boiler-in/$areaSlug'
      path: '/gas-boiler-in/$areaSlug'
      fullPath: '/gas-boiler-in/$areaSlug'
      preLoaderRoute: typeof GasBoilerInAreaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$refId': {
      id: '/confirmation/$refId'
      path: '/confirmation/$refId'
      fullPath: '/confirmation/$refId'
      preLoaderRoute: typeof ConfirmationRefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$areaSlug': {
      id: '/areas/$areaSlug'
      path: '/areas/$areaSlug'
      fullPath: '/areas/$areaSlug'
      preLoaderRoute: typeof AreasAreaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/admin/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categoryArea/$service': {
      id: '/$categoryArea/$service'
      path: '/$categoryArea/$service'
      fullPath: '/$categoryArea/$service'
      preLoaderRoute: typeof CategoryAreaServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceSlug/how-to': {
      id: '/services/$serviceSlug/how-to'
      path: '/how-to'
      fullPath: '/services/$serviceSlug/how-to'
      preLoaderRoute: typeof ServicesServiceSlugHowToRouteImport
      parentRoute: typeof ServicesServiceSlugRoute
    }
    '/services/$serviceSlug/faqs': {
      id: '/services/$serviceSlug/faqs'
      path: '/faqs'
      fullPath: '/services/$serviceSlug/faqs'
      preLoaderRoute: typeof ServicesServiceSlugFaqsRouteImport
      parentRoute: typeof ServicesServiceSlugRoute
    }
    '/services/$serviceSlug/$areaSlug': {
      id: '/services/$serviceSlug/$areaSlug'
      path: '/$areaSlug'
      fullPath: '/services/$serviceSlug/$areaSlug'
      preLoaderRoute: typeof ServicesServiceSlugAreaSlugRouteImport
      parentRoute: typeof ServicesServiceSlugRoute
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ReviewsRouteChildren {
  ReviewsServiceSlugRoute: typeof ReviewsServiceSlugRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsServiceSlugRoute: ReviewsServiceSlugRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

interface ServicesServiceSlugRouteChildren {
  ServicesServiceSlugAreaSlugRoute: typeof ServicesServiceSlugAreaSlugRoute
  ServicesServiceSlugFaqsRoute: typeof ServicesServiceSlugFaqsRoute
  ServicesServiceSlugHowToRoute: typeof ServicesServiceSlugHowToRoute
}

const ServicesServiceSlugRouteChildren: ServicesServiceSlugRouteChildren = {
  ServicesServiceSlugAreaSlugRoute: ServicesServiceSlugAreaSlugRoute,
  ServicesServiceSlugFaqsRoute: ServicesServiceSlugFaqsRoute,
  ServicesServiceSlugHowToRoute: ServicesServiceSlugHowToRoute,
}

const ServicesServiceSlugRouteWithChildren =
  ServicesServiceSlugRoute._addFileChildren(ServicesServiceSlugRouteChildren)

interface ServicesRouteChildren {
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRouteWithChildren
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceSlugRoute: ServicesServiceSlugRouteWithChildren,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CommercialRoute: CommercialRoute,
  ComplaintsRoute: ComplaintsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  EmergencyRoute: EmergencyRoute,
  FaqRoute: FaqRoute,
  FinanceRoute: FinanceRoute,
  LandlordRoute: LandlordRoute,
  NewsRoute: NewsRouteWithChildren,
  OurStoryRoute: OurStoryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRouteWithChildren,
  SafetyRoute: SafetyRoute,
  ServiceRequestRoute: ServiceRequestRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  WhyTrustUsRoute: WhyTrustUsRoute,
  WorkRoute: WorkRouteWithChildren,
  CategoryAreaServiceRoute: CategoryAreaServiceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AreasAreaSlugRoute: AreasAreaSlugRoute,
  ConfirmationRefIdRoute: ConfirmationRefIdRoute,
  GasBoilerInAreaSlugRoute: GasBoilerInAreaSlugRoute,
  HeatingInAreaSlugRoute: HeatingInAreaSlugRoute,
  AreasIndexRoute: AreasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
